import { OpenAI } from 'openai';

// Inicializar perezosamente para no romper el build de Next.js si la variable no está en el entorno local
let openaiInstance: OpenAI | null = null;
function getOpenAI() {
  if (!openaiInstance) {
    openaiInstance = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY || 'dummy_key_for_build',
    });
  }
  return openaiInstance;
}

export type GeneratedPost = {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  seo_title: string;
  seo_description: string;
  keywords: string[]; // Autogenerated or refined keywords
  cover_image_alt: string;
  cover_image_prompt: string; // Prompt used for DALL-E image generation
};

/**
 * Genera un artículo de blog SEO-optimizado con imagen de portada
 */
export async function generateBlogPost(topic: string, keywords: string[], sources?: string, mode: 'basic' | 'advanced' = 'basic'): Promise<GeneratedPost & { cover_image: string }> {
  const isAdvanced = mode === 'advanced';
  
  const prompt = `
    Actúa como experto de ÉLITE en SEO Técnico, Ingeniería Web y Estrategia de Negocios Digitales para Webunica.cl, la agencia líder en Shopify, Next.js y SaaS en Chile.
    
    TEMA: ${topic}
    PALABRAS CLAVE INICIALES: ${keywords.join(', ')}
    FUENTES DE CONSULTA: ${sources || 'No se proporcionaron fuentes adicionales.'}
    MODO: ${isAdvanced ? 'INGENIERÍA AVANZADA / MASTERCLASS' : 'ESTÁNDAR EDUCATIVO'}
    
    REGLAS DE CONTENIDO:
    1. EXTENSIÓN: ${isAdvanced ? 'Mínimo 1800 palabras. Desarrolla cada punto con profundidad técnica quirúrgica.' : 'Mínimo 1000 palabras.'}
    2. ESTRUCTURA: HTML semántico (solo <p>, <h2>, <h3>, <h4>, <ul>, <li>, <strong>, <em>, <blockquote>, <pre>, <code>).
    3. ${isAdvanced ? 'INCLUYE BLOQUES DE CÓDIGO (usando <pre><code>...</code></pre>) con ejemplos reales en React, Shopify Liquid, JSON o Shell según corresponda.' : 'Enfoque en conceptos claros y beneficios.'}
    4. TONO: ${isAdvanced ? 'Experto, técnico, autoritario pero accesible. Habla de arquitectura, performance (LCP, INP), seguridad y escalabilidad.' : 'Profesional, persuasivo y educativo.'}
    5. SEO: Utiliza la información de las FUENTES DE CONSULTA para enriquecer el contenido. Incluye al menos 5 subtítulos (H2 y H3) optimizados semánticamente.
    6. CTA: Intro de alto impacto + conclusión con Call to Action estratégico hacia los servicios de consultoría avanzada de Webunica.cl.
    7. Identifica y genera las mejores 8 PALABRAS CLAVE SEO para este artículo.
    
    RESPONDE ÚNICAMENTE EN JSON:
    {
      "title": "Título H1 disruptivo con keyword principal",
      "slug": "url-amigable-seo",
      "excerpt": "Resumen técnico de 150 chars máx",
      "content": "<p>HTML del artículo...</p>",
      "seo_title": "Título SEO (máx 60 chars)",
      "seo_description": "Meta descripción SEO (máx 160 chars) con alto CTR",
      "keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5", "keyword6", "keyword7", "keyword8"],
      "cover_image_alt": "Alt descriptivo SEO para imagen (máx 120 chars)",
      "cover_image_prompt": "Prompt en inglés para DALL-E 3: high-end 3D tech render or professional minimalist illustration of [tema], deep purple and emerald green neon accents, dark mode aesthetic, cinematic lighting, 8k, professional, no text"
    }
  `;

  const openai = getOpenAI();
  // 1. Generamos el texto del artículo
  const textResponse = await openai.chat.completions.create({
    model: 'gpt-4o',
    messages: [{ role: 'user', content: prompt }],
    response_format: { type: 'json_object' },
    temperature: 0.7,
  });

  const textContent = textResponse.choices[0].message.content;
  if (!textContent) throw new Error('No se generó contenido de texto');

  const postData = JSON.parse(textContent) as GeneratedPost;

  // 2. Generamos la imagen de portada con DALL-E 3
  let cover_image = '';
  try {
    const openai = getOpenAI();
    const imageResponse = await openai.images.generate({
      model: 'dall-e-3',
      prompt: postData.cover_image_prompt || 
        `Modern flat design illustration about "${topic}" for a web development agency in Chile. Purple #8B5CF6 and green #10B981 brand colors, minimalist, professional, no text in image.`,
      n: 1,
      size: '1792x1024', // Landscape para imagen de portada de blog
      quality: 'standard',
    });
    
    const tempUrl = imageResponse.data?.[0]?.url;
    
    if (tempUrl) {
      // DALL-E URLs caducan en 60 mins. Debemos descargarla y guardarla permanentemente.
      const imgRes = await fetch(tempUrl);
      const imgBuffer = await imgRes.arrayBuffer();

      const { getSupabaseAdmin } = await import('./supabase/admin');
      const adminClient = getSupabaseAdmin();
      
      const fileName = `${postData.slug.substring(0,40)}-${Date.now()}.png`;

      // Subimos a Supabase Storage (Bucket "blog")
      const { error } = await adminClient.storage
        .from('blog')
        .upload(fileName, Buffer.from(imgBuffer), { contentType: 'image/png', upsert: true });

      if (error) {
        // Fallback: intentar crear el bucket si no existe
        if (error.message.toLowerCase().includes('bucket not found') || error.message.toLowerCase().includes('not found')) {
            await adminClient.storage.createBucket('blog', { public: true });
            await adminClient.storage.from('blog').upload(fileName, Buffer.from(imgBuffer), { contentType: 'image/png', upsert: true });
        } else {
            console.error('[openai] Error subiendo imagen a Supabase Storage:', error);
            throw error; // Ir al catch
        }
      }

      // Obtener URL pública
      const { data: pubData } = adminClient.storage.from('blog').getPublicUrl(fileName);
      cover_image = pubData.publicUrl;
    }
  } catch (imgError) {
    console.warn('[openai] DALL-E generation or upload failed, using placeholder:', imgError);
    // Fallback: imagen genérica de Unsplash con query relevante
    const query = encodeURIComponent(keywords[0] || topic);
    cover_image = `https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80`;
  }

  return {
    ...postData,
    cover_image,
  };
}
