import { OpenAI } from 'openai';

// Inicializar perezosamente para no romper el build de Next.js si la variable no está en el entorno local
let openaiInstance: OpenAI | null = null;
function getOpenAI() {
  if (!openaiInstance) {
    openaiInstance = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY || 'dummy_key_for_build',
    });
  }
  return openaiInstance;
}

export type GeneratedPost = {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  seo_title: string;
  seo_description: string;
  keywords: string[]; // Autogenerated or refined keywords
  cover_image_alt: string;
  cover_image_prompt: string; // Prompt used for DALL-E image generation
};

/**
 * Genera un artículo de blog SEO-optimizado con imagen de portada
 */
export async function generateBlogPost(topic: string, keywords: string[], sources?: string, mode: 'basic' | 'advanced' = 'basic'): Promise<GeneratedPost & { cover_image: string; cover_image_error?: string }> {
  const isAdvanced = mode === 'advanced';
  
  const prompt = `
    Actúa como Consultor Estratégico Senior y Redactor de Negocios para Webunica.cl, la agencia líder en desarrollo de Tiendas en Línea Shopify, Sitios Web Corporativos y Estrategia Digital en Chile.
    
    TEMA: ${topic}
    PALABRAS CLAVE INICIALES: ${keywords.join(', ')}
    FUENTES DE CONSULTA: ${sources || 'No se proporcionaron fuentes adicionales.'}
    MODO: ${isAdvanced ? 'ESTRATEGIA AVANZADA Y CRECIMIENTO B2B' : 'ESTÁNDAR EDUCATIVO COMERCIAL'}
    
    AUDIENCIA: Emprendedores, dueños de negocios, gerentes comerciales y tomadores de decisiones B2B en Chile. NO tienen conocimientos de programación ni tecnicismos informáticos. Buscan resultados de negocio, presencia profesional, aumento de ventas, credibilidad y optimización de conversión.
    
    REGLAS DE CONTENIDO:
    1. EXTENSIÓN: ${isAdvanced ? 'Mínimo 1500 palabras. Desarrolla a fondo estrategias comerciales, embudos de venta y mejores prácticas de ecommerce.' : 'Mínimo 1000 palabras.'}
    2. ESTRUCTURA: HTML semántico limpio (solo <p>, <h2>, <h3>, <h4>, <ul>, <li>, <strong>, <em>, <blockquote>). NO uses etiquetas <pre> ni <code> de código técnico a menos que sea estrictamente necesario para un ejemplo conceptual muy simple de negocio.
    3. ENFOQUE: Centrado en BENEFICIOS y RESULTADOS comerciales. Si hablas de velocidad web, explícalo como "carga rápida para no perder ventas y retener clientes" en lugar de tecnicismos como "LCP o Web Vitals". Explica conceptos difíciles de forma clara y amigable.
    4. TONO: Cercano, empático, profesional, de confianza y de negocios. El lector debe sentir que Webunica entiende su dolor comercial (ventas bajas, sitio desactualizado, sistemas lentos) y que ofrece la solución perfecta.
    5. SEO: Utiliza la información de las FUENTES DE CONSULTA de manera persuasiva. Incluye al menos 5 subtítulos (H2 y H3) atractivos para lectura rápida y escaneo visual.
    6. CTA (Llamado a la Acción): Integrar un llamado a la acción persuasivo al final del artículo invitando a agendar una asesoría gratuita con Webunica.cl para diseñar su sitio web profesional o tienda Shopify a medida.
    7. Genera las mejores 8 PALABRAS CLAVE SEO orientadas a búsquedas de clientes de negocios (búsquedas comerciales, no técnicas).
    
    RESPONDE ÚNICAMENTE EN JSON:
    {
      "title": "Título H1 persuasivo orientado a negocios y beneficios, con la keyword principal",
      "slug": "url-amigable-seo",
      "excerpt": "Resumen persuasivo enfocado en los beneficios del artículo (máx 150 chars)",
      "content": "<p>HTML del artículo...</p>",
      "seo_title": "Título SEO comercial (máx 60 chars)",
      "seo_description": "Meta descripción que despierte curiosidad e impulse el clic desde Google (máx 160 chars)",
      "keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5", "keyword6", "keyword7", "keyword8"],
      "cover_image_alt": "Alt descriptivo comercial para SEO de la imagen (máx 120 chars)",
      "cover_image_prompt": "Prompt en inglés para DALL-E 3: Elegant, clean, professional minimalist flat illustration or high-end 3D digital scene representing [tema] in a business/commerce context. Corporate theme, bright lighting, clean background, violet (#8B5CF6) and soft green/emerald accents, professional, modern B2B brand aesthetic, no text, no words"
    }
  `;

  const openai = getOpenAI();
  // 1. Generamos el texto del artículo
  const textResponse = await openai.chat.completions.create({
    model: 'gpt-4o',
    messages: [{ role: 'user', content: prompt }],
    response_format: { type: 'json_object' },
    temperature: 0.7,
  });

  const textContent = textResponse.choices[0].message.content;
  if (!textContent) throw new Error('No se generó contenido de texto');

  const postData = JSON.parse(textContent) as GeneratedPost;

  // 2. Generamos la imagen de portada con DALL-E 3
  let cover_image = '';
  let cover_image_error = '';
  try {
    const openai = getOpenAI();
    const imageResponse = await openai.images.generate({
      model: 'dall-e-3',
      prompt: postData.cover_image_prompt || 
        `Modern flat design illustration about "${topic}" for a web development agency in Chile. Purple #8B5CF6 and green #10B981 brand colors, minimalist, professional, no text in image.`,
      n: 1,
      size: '1792x1024', // Landscape para imagen de portada de blog
      quality: 'standard',
    });
    
    const tempUrl = imageResponse.data?.[0]?.url;
    
    if (tempUrl) {
      // DALL-E URLs caducan en 60 mins. Debemos descargarla y guardarla permanentemente.
      const imgRes = await fetch(tempUrl);
      const imgBuffer = await imgRes.arrayBuffer();

      const { getSupabaseAdmin } = await import('./supabase/admin');
      const adminClient = getSupabaseAdmin();
      
      const fileName = `${postData.slug.substring(0,40)}-${Date.now()}.png`;

      // Subimos a Supabase Storage (Bucket "blog")
      const { error } = await adminClient.storage
        .from('blog')
        .upload(fileName, Buffer.from(imgBuffer), { contentType: 'image/png', upsert: true });

      if (error) {
        // Fallback: intentar crear el bucket si no existe
        if (error.message.toLowerCase().includes('bucket not found') || error.message.toLowerCase().includes('not found')) {
            await adminClient.storage.createBucket('blog', { public: true });
            await adminClient.storage.from('blog').upload(fileName, Buffer.from(imgBuffer), { contentType: 'image/png', upsert: true });
        } else {
            console.error('[openai] Error subiendo imagen a Supabase Storage:', error);
            throw error; // Ir al catch
        }
      }

      // Obtener URL pública
      const { data: pubData } = adminClient.storage.from('blog').getPublicUrl(fileName);
      cover_image = pubData.publicUrl;
    }
  } catch (imgError: any) {
    console.warn('[openai] DALL-E generation or upload failed, using placeholder:', imgError);
    cover_image_error = imgError?.message || String(imgError);
    
    // Fallback: imagen variada de negocios, ecommerce y crecimiento de Unsplash usando hash de la URL (DJB2 para evitar colisiones)
    const placeholders = [
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80', // Laptop metrics/growth
      'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80', // Corporate planning/consulting
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&q=80', // Teamwork project kickoff
      'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80', // Ecommerce payments / credit card sales
      'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=1200&q=80', // Elegant retail online shop background
      'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1200&q=80', // Business handshake deal
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80', // Digital screen planning
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80', // Corporate skyscrapers
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1200&q=80', // Business executive presentation
      'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1200&q=80', // Team success startup
      'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&q=80', // Workspace notebook and glasses
      'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80', // Charts on table with keyboard
      'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=1200&q=80', // Corporate training speaker
      'https://images.unsplash.com/photo-1542744094-3a31f103e35f?w=1200&q=80', // Meeting room graph explanation
      'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=1200&q=80', // Macbook and workspace tools
      'https://images.unsplash.com/photo-1552581230-c01591d6f29a?w=1200&q=80', // Creative brainstorming notes
      'https://images.unsplash.com/photo-1513258496099-48168024aec0?w=1200&q=80', // Typing on keyboard
      'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=1200&q=80', // Grow plant / economy / B2B growth
      'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&q=80', // Flowcharts dashboard design UI
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&q=80'  // Group pointing at screen
    ];
    
    // Algoritmo de hash DJB2 para asegurar excelente distribución y evitar colisiones
    const hash = (postData.slug || topic).split('').reduce((acc, char) => {
      return ((acc << 5) + acc) + char.charCodeAt(0);
    }, 5381);
    
    const index = Math.abs(hash) % placeholders.length;
    cover_image = placeholders[index];
  }

  return {
    ...postData,
    cover_image,
    cover_image_error: cover_image_error || undefined,
  };
}
